
export default {
	// 用户
	__EVENT__USERINFO__: "__EVENT__USERINFO__",

	__EVENT__TOC__IN__: "__EVENT__TOC__IN__",
	__EVENT__TOC__IN__TEXT__: "__EVENT__TOC__IN__TEXT__",

	__EVENT__MARKDOWN_EX__IN__TEXT__: "__EVENT__MARKDOWN_EX__IN__TEXT__",

	__EVENT__EDITOR__CURRENT__PAGE__: "__EVENT__EDITOR__CURRENT__PAGE__",
	__EVENT__CODEMIRROR__IN__PAGE__: "__EVENT__CODEMIRROR__IN__PAGE__",
	__EVENT__CODEMIRROR__IN__SAVE__: "__EVENT__CODEMIRROR__IN__SAVE__",
	__EVENT__CODEMIRROR__IN__TEXT_REPLACE__: "__EVENT__CODEMIRROR__IN__TEXT_REPLACE__",
	__EVENT__CODEMIRROR__OUT__TEXT__: "__EVENT__CODEMIRROR__OUT__TEXT__",

	__EVENT__TAG__CURRENT_TAG__: "__EVENT__TAG__CURRENT_TAG__",
	__EVENT__TAG__SET_ROOT_TAG__: "__EVENT__TAG__SET_ROOT_TAG__",
	__EVENT__TAG__GET_ROOT_TAG__: "__EVENT__TAG__GET_ROOT_TAG__",
	__EVENT__TAG__MODE__: "__EVENT__TAG__MODE__",

	// 编辑器事件
	__EVENT__FILETREE__OUT__PAGE__: "__EVENT__FILETREE__OUT__PAGE__",
}
